### ISSUE TITLE
Setup.gateways should set the CoGateway address on the Utility Token

### ISSUE THREAD

**Issue by 0xsarvesh** [OpenST/mosaic.js#129]
In https://github.com/OpenSTFoundation/mosaic.js/blob/develop/src/Setup/gateways.js, it is missing the step to set the utility token's co-gateway address to that of the deployed co-gateway.

**Comment by benjaminbollen** [comment]
rather; given a UT and an organization, deploy the gateway.  From BT we need to be able to deploy a UBT and organization - and *then* call mosaic to deploy gateways, given the UBT and its organisation (it can be reused for cogateway)

**Comment by schemar** [comment]
Updated the issue accordingly, please check @benjaminbollen
