### ISSUE TITLE
Give OSTPrime#wrap and #unwrap a more similar interface

### ISSUE THREAD

**Issue by hobofan** [OpenST/mosaic.js#138]
The current interfaces look like this:

`OSTPrime.wrap(txOptions)` (where the amount is specified via `txOptions.value` and

`OSTPrime.unwrap(amount, txOptions)`.

However a consumer shouldn't care that the underlying implementation detail is that `wrap` is handled via a payable function. In my opinion it would be nice if `OSTPrime.wrap` would also take a `amount` parameter, to have a more uniform interface.

**Comment by schemar** [comment]
I think so, too 👍
