### ISSUE TITLE
Facilitator should only attempt proof at valid heights

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic.js#147]
Given that I facilitate to progress stake/redeem
When the latest available state root on target is lower than the height of stake/redeem
Then the facilitator should not attempt the proof
And provide an error to the user

Can be log and/or return error.

In order to know the block height of stake/redeem, the facilitator should return the block number as part of the stake/redeem response.
The facilitator should accept the block number as argument on progress stake/redeem.

**Comment by abhayks1** [comment]
As per the ticket description, blockNumber argument has been added in progressStake and progressMint facilitator functions. This changes the interface of progressStake and progressMint functions. JLP consumes these facilitator functions.

@benjaminbollen how should we proceed on this ticket and the PR? 
Should it be merged to develop and new npm published for JLP to integrate?
Moving it to "Parking Lot" till it's clarified.

**Comment by benjaminbollen** [comment]
yes, it should go onto develop.
