### ISSUE TITLE
Fix the known security vulnerabilities

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/mosaic.js#174]
Analyze and fix the known security vulnerabilities detected in the following repositories

OpenST / mosaic-contracts
OpenST / openst.js
OpenST / mosaic.js
OpenST / mosaic-chains	
OpenST / organization-contracts
OpenST / brandedtoken.js
OpenST / utilitytoken-contracts

Update the dependency to the latest version
tar	Version < 4.4.2	Upgrade to ~> 4.4.2

**Comment by schemar** [comment]
Which dependencies depend on the outdated version of tar?

**Comment by deepesh-kn** [comment]
> Which dependencies depend on the outdated version of tar?

One was `webpack`
