### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/mosaic.js#36]
- getting started instructions

**Comment by schemar** [comment]
* introduction
* licenses
* ci badge
* npm badge
* code of conduct

**Comment by schemar** [comment]
Check which license it should be under and make sure that it is set to the correct one.

**Comment by schemar** [comment]
License will be set in #54

**Comment by deepesh-kn** [comment]
Also, add contents of FACILITATOR.md in the readme file.
