### ISSUE TITLE
Add CLI structure

### ISSUE THREAD

**Issue by hobofan** [OpenST/mosaic.js#43]
Add a `mosaic` CLI command that allows for running individual one-off processes.

The CLI should be able to read a configuration file to get all the individual parameters for the required action.

**Comment by hobofan** [comment]
My proposal would be to make the CLI structured around subcommands.
- All commands should take a config file as input.
- Optionally, missing parameters should be inquired.
- The commands should print a summary of what they are going to do and ask for approval before sending any transactions.
- If the action of the command produces any output it should write it to a file that can be read as input by the next command.

An example of a command execution would be:
`mosaic gateway activate --config mosaic.config.json`

**Comment by benjaminbollen** [comment]
1. would the same `config.json` serve as input to a sequence of actions? ie. the action reads the values it is concerned about?
2. an on-screen wizard is surely great but can be considered a stretch goal; failure with a helpful error on which parameter is missing; or which problem occurred would be sufficient

**Comment by benjaminbollen** [comment]
other thoughts that come to mind in no specific order:
- if a hashlock's secret is written to a file, for now it does not need to be encrypted
- the state-progression file could have a list `messages` which has the message hashes of all the message to perform this action for (and skip if already performed)

**Comment by hobofan** [comment]
> would the same config.json serve as input to a sequence of actions? ie. the action reads the values it is concerned about?

Yes, I was thinking that the same file is used for multiple actions. I am not sure yet how that would work together with the outputs of a previous action. Maybe via separate `--config` and `--input` files, where the config file contains more general configuration (like RPC endpoints and contract addresses) .

**Comment by schemar** [comment]
Closing as invalid. Currently, we're not planning on supporting CLI for mosaic.js
