### ISSUE TITLE
Deprecate AbiBinProvider constructor arguments

### ISSUE THREAD

**Issue by hobofan** [OpenST/mosaic.js#50]
Internally in `mosaic.js` we don't use and are deprecating the `abiFolderPath` and `binFolderPath` parameters for the `AbiBinProvder` constructor anymore, as we bundle the contracts abis and bins directly into the package by requiring it from `mosaic-contracts`. This also had the added benefit of not having a dependency on the node system modules `path` and `fs` anymore.

## Migrating away
As both [brandedtoken.js](https://github.com/OpenSTFoundation/brandedtoken.js) and [openst.js](https://github.com/OpenSTFoundation/openst.js) are currently using the parameters, we are providing instructions to migrate away from them.

**The plan is to remove support for the paramters in the next release after `0.10.0`**.

The rough approach in both options is the same. Instead of trying to load the ABIs/bins from the file system when they are requested, all the available ABIs and bins are added to the provider during its construction via `.addABI` and `.addBIN`.

### Option 1 (recommended) - load ABIs and bins from a json/js file

The idea here is to put all the ABIs and bins into a single file (or multiple files), and expose them via a single js module that can be `require`d.

The pseudocode for this looks like this:
```js
const contracts = require('../path/to/my/contracts.js'); // can also be a JSON file, as JS allows for direct requiring of JSON files

class MyAbiBinProvider extends AbiBinProvider {
  constructor() {
    super();
    contracts.forEach((contractName, contractContent) => {
      this.addABI(contractName, contractContent.abi);
      if (contractContent.bin) { // Interfaces don't have bins
        this.addBIN(contractName, contractContent.bin);
      }
    });
  }
}
```

### Option 2 - keeping the `fs` and `path` dependencies

Use code similar to the one we have in [AbiBinProvider-node.js](https://github.com/OpenSTFoundation/mosaic.js/blob/a3410f420591145b33e3f95746ed1b1787aa4173/src/AbiBinProvider-node.js#L6), to loop over all the ABI and bin files found in the directories and add them to the provider via `.addABI` and `.addBIN`.

**Comment by abhayks1** [comment]
One issue I see in both approaches is that ABIs and BINs of all contracts will be loaded in memory. 
Food for thought for next release considering size of ABIs and BINs will be large.
cc: @hobofan @schemar

**Comment by hobofan** [comment]
I'm not sure if that is significant enough to be a problem. I ran webpack-bundle-analyzer over the bundle we generate from mosaic.js and the size of all ABIs and bins was ~400kb total.

Of course the in-memory representation of the parsed JSON is usually bigger than that, but if that is really a problem, we can hold them in memory as strings (which should be very efficient) and only parse them as necessary.

Another way how we can optimize the effective impact is that we could expose the ABIs and bins from mosaic-contracts as ES6 modules, and then webpack can perform code-splitting and tree-shaking to only include the ABIs and bins that are actually used in the application.
