### ISSUE TITLE
Deprecate StakeHelper

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic.js#86]
`StakeHelper` has been deprecated in favor of `Facilitator`, `Staker`, and `Contracts`.

`Contracts` provides you with all the methods for all the contracts.

```js
const Mosaic = require('mosaic.js');
const { Contracts } = Mosaic;

const gateway = new Contracts.EIP20Gateway(web3, address);
```

You can use the `Facilitator` and `Staker` as helpers.

**Comment by deepesh-kn** [comment]
Currently, we just have just `approve` methods in Staker.
Should we move the `stake` method from Facilitator to Staker?
And`Facilitator.stake` will internally call the `Staker.stake`.

similarly for the Redeemer?

**Comment by schemar** [comment]
Maybe the `Facilitator` is sufficient. Should I mention the facilitator instead of the staker in the above issue?
